# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Transformers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Transformers
  
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'MYPassthrough'

  target 'TransformersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TransformersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
